name: Build Status

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16.13.2]

    steps:
    - uses: actions/checkout@v2

    - name: Upgrade NPM
      run: npm install -g npm

    - name: Use Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    # basically npm install but only installs from package-lock
    - run: npm ci
    - run: npm run lint
    - run: npm run test